server:
  port: 8097
  servlet:
    context-path: /changan

spring:
  datasource:

    url: jdbc:postgresql://125.220.153.25:5432/roadnetwork_henan #    url: jdbc:mysql://localhost:3306/tis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: postgres
    password: ypfamily608
    driverClassName: org.postgresql.Driver
  jackson:
    time-zone: GMT+8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update #框架会自动帮我们创建或更新表结构
  neo4j:
    uri: bolt://125.220.153.22:7687
    authentication:
      username: neo4j
      password: neo4jj
